"""Added uniqueness to api key

Revision ID: 932eb02b1a49
Revises: 94dabf8ad665
Create Date: 2026-01-04 17:57:17.696975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932eb02b1a49'
down_revision: Union[str, Sequence[str], None] = '94dabf8ad665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikeys_key'), table_name='apikeys')
    op.create_index(op.f('ix_apikeys_key'), 'apikeys', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikeys_key'), table_name='apikeys')
    op.create_index(op.f('ix_apikeys_key'), 'apikeys', ['key'], unique=False)
    # ### end Alembic commands ###
