"""added role

Revision ID: 94dabf8ad665
Revises: 1cd190fe9e88
Create Date: 2026-01-03 17:24:58.677066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "94dabf8ad665"
down_revision: Union[str, Sequence[str], None] = "1cd190fe9e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "apikeys", ["id"])
    op.add_column(
        "users", sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "role")
    op.drop_constraint(None, "apikeys", type_="unique")
    # ### end Alembic commands ###
